find_package(GTest CONFIG REQUIRED)
include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/GammaTest.cmake)

add_subdirectory(GammaCommon)
add_subdirectory(GammaNetwork)
add_subdirectory(GammaScript)
add_subdirectory(GammaConnects)
add_subdirectory(GammaDatabase)
add_subdirectory(GammaMTDbs)
add_subdirectory(GammaShm)
add_subdirectory(GameApp)
add_subdirectory(ModuleGate)
add_subdirectory(ModuleLogin)
add_subdirectory(ModuleCenter)
add_subdirectory(ModuleGame)
add_subdirectory(ModuleDBMain)
